version: '3.7'
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
  browser:
    image: selenium/chrome
    links:
      - hub
  units:
    build:
      context: .
      args:
        ENVIRONMENT: test
    entrypoint: rspec
    volumes:
      - $PWD:/app
    environment:
      LOAD_PATH: "/app/spec;/app/lib"
    working_dir: /app
    command:
      - "--fail-fast"
      - "--pattern"
      - "spec/**/*_spec.rb"
